name: Frontend Cypress Test

on: [push]

jobs:
  test:
    name: Run Frontend Cypress Test
    runs-on: ubuntu-latest
    container: cypress/included:3.8.3
    strategy:
      matrix:
        machines: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Connect and test
        uses: cypress-io/github-action@v1
        with:
          record: true
          parallel: true
          group: "Actions example"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
